blog/urls.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

books/urls.py
from django.conf.urls import url
from django.contrib import admin
#. means current directory
from . import views
#Introduction to namespace, define a namespace here
app_name = 'books'

#define URL pattern for books
#To tell python when we redirect to this, we want to call index() in views file
urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    #/books/2 (2 is the id)
    url(r'^(?P<book_id>[0-9]+)/$', views.detail, name = 'detail'),

]

books/models.py
#to create database or database tables so that site has relevant data
from __future__ import unicode_literals

from django.db import models

# Create your models here.
# First define the structure of database
class Book(models.Model): #Creating a book table here
    name = models.CharField(max_length = 100) # Character field of maximum length 100
    author = models.CharField(max_length = 100)
    price = models.CharField(max_length=100)
    category = models.CharField(max_length=100)
    def __str__(self):
        return self.name + '-' + self.author

#Create a new table here if you want
class table_name(models.Model):
    pass

books/views.py
#Front end of the app/website: What actually gets displayed on the webpage
from django.shortcuts import render
from .models import Book
from django.template import loader
from django.http import Http404

# Create your views here.
from django.http import HttpResponse
from django.shortcuts import render
#A view is a webpage. In order to access it, certain URLs need to be entered
def detail(request, book_id):
    #return HttpResponse("<h2>Details for Book Id:" + str(book_id) + "</h2>")
    try:
        book = Book.objects.get(id = book_id)
    except Book.DoesNotExist:
        raise Http404("This book does not exist")
    return render(request, 'books/detail.html', {'book' :book})




def index(request):
    '''
    #this is what the User is going to see
    #connect to the database to get information from it
    all_books = Book.objects.all()
    html = ''
    for each in all_books:
        url = '/books/' + str(each.id) + "/"
        html+='<a href="' + url +'">' + str(each.name) +'</a><br>'
    return HttpResponse(html)
    '''
    all_books = Book.objects.all()
    #template = loader.get_template('books/index.html')
    #Provide context
    context = {
        'all_books': all_books
    }
    #render the template
    #return HttpResponse(template.render(context, request))
    return render(request,'books/index.html', context )

books/templates/books/detail.html
<h1>{{book.name}}</h1>
<h4>{{book.author}}</h4>

books/templates/books/index.html
{% load staticfiles %}
<html>
    <head>
    <link rel="stylesheet" type="text/css" href="{%static 'books/style.css' %}">
        <!-- Latest compiled and minified CSS  Bootstrap-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    </head>
    <body>

    <nav class = "navbar navbar-inverse">
        <div class =" container-fluid">
            <a class = "navbar-brand" href="{% url 'books:index' %}">The Book Store</a>
            <div class = "collapse navbar-collapse">
            <ul class = "nav navbar-nav">
                <li class ="">
                    <a href="{% url 'books:index' %}">
                        <!-- Icon Image -->
                        <span class = "glyphicon glyphicon-book" aria-hidden ="true"></span>&nbsp;Books
                    </a>
                </li>
            </ul>
                <ul class = "nav navbar-nav navbar-right">
                <li class ="">
                    <a href="{% url 'books:index' %}">
                        <!-- Icon Image -->
                        <span class = "glyphicon glyphicon-plus-sign" aria-hidden ="true"></span>&nbsp; Add Books
                    </a>
                </li>
                    <li class ="">
                    <a href="{% url 'books:index' %}">
                        <!-- Icon Image -->
                        <span class = "glyphicon glyphicon-log-out" aria-hidden ="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>
        </div>
        </div>

    </nav>
    <ul>
        {% for book in all_books %}
            <!-- Static Hardcoded URLS
            <li><a href="/books/{{book.id}}/">{{book.name}}</a></li>
            Introduction to namespace

            -->
            <!-- Refer to detail which belongs to book app otherwise just detail would have worked
            -->
            <li><a href="{% url 'books:detail' book.id %}">{{book.name}}</a></li>
        {% endfor %}
    </ul>

    </body>
</html>